import type React from "react";
import { Card, PageTitle } from "@/components/ui";
import { prisma } from "@/lib/prisma";
import { createPerson, deletePerson, updatePerson } from "./actions";

export default async function PeoplePage() {
  const [people, locations] = await Promise.all([prisma.person.findMany({ include: { location: true }, orderBy: { name: "asc" } }), prisma.location.findMany({ orderBy: { name: "asc" } })]);
  return <><PageTitle title="Pessoas" description="CRUD completo de colaboradores e responsáveis." /><Card><h2 className="mb-3 font-semibold">Nova pessoa</h2><form action={createPerson} className="grid gap-3 md:grid-cols-3"><Input name="name" placeholder="Nome" required /><Input name="email" placeholder="E-mail" /><Input name="employeeCode" placeholder="Matrícula" /><Input name="document" placeholder="Documento" /><Input name="department" placeholder="Departamento" /><select name="locationId" className="rounded-xl border p-2"><option value="">Sem localização</option>{locations.map((l) => <option key={l.id} value={l.id}>{l.name}</option>)}</select><input type="hidden" name="personType" value="EMPLOYEE" /><button className="rounded-xl bg-slate-950 px-4 py-2 text-white">Criar</button></form></Card><div className="mt-5 space-y-3">{people.map((p) => <Card key={p.id}><form action={updatePerson} className="grid gap-3 md:grid-cols-7"><input type="hidden" name="id" value={p.id} /><Input name="name" defaultValue={p.name} /><Input name="email" defaultValue={p.email ?? ""} /><Input name="employeeCode" defaultValue={p.employeeCode ?? ""} /><Input name="document" defaultValue={p.document ?? ""} /><Input name="department" defaultValue={p.department ?? ""} /><select name="locationId" defaultValue={p.locationId ?? ""} className="rounded-xl border p-2"><option value="">Sem localização</option>{locations.map((l) => <option key={l.id} value={l.id}>{l.name}</option>)}</select><label className="flex items-center gap-2 text-sm"><input name="active" type="checkbox" defaultChecked={p.active} />Ativo</label><button className="rounded-xl border px-3 py-2">Salvar</button></form><form action={deletePerson} className="mt-2"><input type="hidden" name="id" value={p.id} /><button className="text-sm text-red-700">Excluir</button></form></Card>)}</div></>;
}
function Input(props: React.InputHTMLAttributes<HTMLInputElement>) { return <input {...props} className="rounded-xl border border-slate-300 px-3 py-2" />; }
