import type React from "react";
import { Card, PageTitle } from "@/components/ui";
import { locationTypes, locationTypeLabels, type LocationTypeValue } from "@/lib/format";
import { prisma } from "@/lib/prisma";
import { createLocation, deleteLocation, updateLocation } from "./actions";

export default async function LocationsPage() {
  const locations = await prisma.location.findMany({ include: { parentLocation: true }, orderBy: { name: "asc" } });
  return <><PageTitle title="Localizações" description="CRUD completo de bases, lojas e áreas internas." /><Card><h2 className="mb-3 font-semibold">Nova localização</h2><form action={createLocation} className="grid gap-3 md:grid-cols-3"><Input name="name" placeholder="Nome" required /><Input name="code" placeholder="Código" required /><TypeSelect /><Input name="address" placeholder="Endereço" /><ParentSelect locations={locations} /><label className="flex items-center gap-2 text-sm"><input name="isGovernanceBase" type="checkbox" />Base de governança</label><button className="rounded-xl bg-slate-950 px-4 py-2 text-white">Criar</button></form></Card><div className="mt-5 space-y-3">{locations.map((l) => <Card key={l.id}><form action={updateLocation} className="grid gap-3 md:grid-cols-8"><input type="hidden" name="id" value={l.id} /><Input name="name" defaultValue={l.name} /><Input name="code" defaultValue={l.code} /><TypeSelect defaultValue={l.type} /><Input name="address" defaultValue={l.address ?? ""} /><ParentSelect locations={locations.filter((x) => x.id !== l.id)} defaultValue={l.parentLocationId ?? ""} /><label className="flex items-center gap-2 text-sm"><input name="active" type="checkbox" defaultChecked={l.active} />Ativa</label><label className="flex items-center gap-2 text-sm"><input name="isGovernanceBase" type="checkbox" defaultChecked={l.isGovernanceBase} />Governança</label><button className="rounded-xl border px-3 py-2">Salvar</button></form><p className="mt-2 text-sm text-slate-500">Pai: {l.parentLocation?.name ?? "—"}</p><form action={deleteLocation} className="mt-2"><input type="hidden" name="id" value={l.id} /><button className="text-sm text-red-700">Excluir</button></form></Card>)}</div></>;
}
function Input(props: React.InputHTMLAttributes<HTMLInputElement>) { return <input {...props} className="rounded-xl border border-slate-300 px-3 py-2" />; }
function TypeSelect({ defaultValue }: { defaultValue?: LocationTypeValue }) { return <select name="type" defaultValue={defaultValue} className="rounded-xl border p-2">{locationTypes.map((t) => <option key={t} value={t}>{locationTypeLabels[t]}</option>)}</select>; }
function ParentSelect({ locations, defaultValue = "" }: { locations: { id: string; name: string }[]; defaultValue?: string }) { return <select name="parentLocationId" defaultValue={defaultValue} className="rounded-xl border p-2"><option value="">Sem pai</option>{locations.map((l) => <option key={l.id} value={l.id}>{l.name}</option>)}</select>; }
