import { notFound } from "next/navigation";
import { Card, PageTitle } from "@/components/ui";
import { assetStatusLabels, assetTypeLabels, formatDate, movementTypeLabels, termStatusLabels, termTypeLabels } from "@/lib/format";
import { prisma } from "@/lib/prisma";

export default async function AssetDetails({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const asset = await prisma.asset.findUnique({ where: { id }, include: { currentLocation: true, currentResponsible: true, movements: { include: { fromLocation: true, toLocation: true }, orderBy: { requestedAt: "desc" } }, responsibilityTerms: { include: { responsible: true }, orderBy: { generatedAt: "desc" } } } });
  if (!asset) notFound();
  return <><PageTitle title={`Ativo ${asset.assetTag}`} description="Dados cadastrais, vínculo atual e histórico." /><div className="grid gap-5 xl:grid-cols-3"><Card><h2 className="mb-4 text-lg font-semibold">Dados do ativo</h2><dl className="space-y-3 text-sm"><Row k="Tipo" v={assetTypeLabels[asset.type]} /><Row k="Status" v={assetStatusLabels[asset.status]} /><Row k="Serial" v={asset.serialNumber} /><Row k="Hostname" v={asset.hostname} /><Row k="Marca/modelo" v={[asset.brand, asset.model].filter(Boolean).join(" ")} /><Row k="Origem" v={asset.origin} /></dl></Card><Card><h2 className="mb-4 text-lg font-semibold">Responsável atual</h2><p className="font-semibold">{asset.currentResponsible?.name ?? "Sem responsável"}</p><p className="text-sm text-slate-500">{asset.currentResponsible?.email ?? "Ativo sem pessoa vinculada"}</p></Card><Card><h2 className="mb-4 text-lg font-semibold">Localização atual</h2><p className="font-semibold">{asset.currentLocation.name}</p><p className="text-sm text-slate-500">{asset.currentLocation.code}</p></Card></div><div className="mt-5 grid gap-5 xl:grid-cols-2"><Card><h2 className="mb-4 text-lg font-semibold">Histórico de movimentações</h2>{asset.movements.length ? <div className="space-y-3">{asset.movements.map((m) => <div key={m.id} className="rounded-xl border border-slate-200 p-4 text-sm"><p className="font-semibold">{movementTypeLabels[m.type]} • {formatDate(m.executedAt ?? m.requestedAt)}</p><p className="text-slate-600">{m.fromLocation?.name ?? "—"} → {m.toLocation?.name ?? "—"}</p><p className="text-slate-500">{m.reason ?? "Sem motivo informado"}</p></div>)}</div> : <p className="text-sm text-slate-500">Nenhuma movimentação encontrada.</p>}</Card><Card><h2 className="mb-4 text-lg font-semibold">Histórico de termos</h2>{asset.responsibilityTerms.length ? <div className="space-y-3">{asset.responsibilityTerms.map((t) => <div key={t.id} className="rounded-xl border border-slate-200 p-4 text-sm"><p className="font-semibold">{t.termNumber} • {termTypeLabels[t.type]}</p><p className="text-slate-600">{t.responsible.name} — {termStatusLabels[t.status]}</p><p className="text-slate-500">Gerado em {formatDate(t.generatedAt)}</p></div>)}</div> : <p className="text-sm text-slate-500">Nenhum termo encontrado.</p>}</Card></div></>;
}
function Row({ k, v }: { k: string; v?: string | null }) { return <div><dt className="text-slate-500">{k}</dt><dd className="font-medium">{v || "—"}</dd></div>; }
