ALTER TYPE "UserRole" RENAME TO "UserRole_old";
CREATE TYPE "UserRole" AS ENUM ('ADMIN', 'TI_CD', 'SUPORTE_LOJAS', 'GESTOR', 'CONSULTA');
ALTER TABLE "User" ALTER COLUMN "role" DROP DEFAULT;
ALTER TABLE "User" ALTER COLUMN "role" TYPE "UserRole" USING (
  CASE "role"::text
    WHEN 'ADMIN' THEN 'ADMIN'
    WHEN 'ASSET_MANAGER' THEN 'TI_CD'
    WHEN 'TECHNICIAN' THEN 'SUPORTE_LOJAS'
    WHEN 'AUDITOR' THEN 'GESTOR'
    ELSE 'CONSULTA'
  END
)::"UserRole";
ALTER TABLE "User" ALTER COLUMN "role" SET DEFAULT 'CONSULTA';
DROP TYPE "UserRole_old";
ALTER TABLE "User" ADD COLUMN "passwordHash" TEXT;
ALTER TABLE "User" RENAME COLUMN "active" TO "isActive";
